apiVersion: v1
kind: Service
metadata:
  name: test-web-service
spec:
  type: LoadBalancer # Azure 공인 IP를 외부 로드밸런서로 즉시 할당받음
  ports:
    - port: 80         # 브라우저에서 접속할 포트 (http://<공인IP>)
      targetPort: 8080
  selector:
    app: test-web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-deployment
spec:
  replicas: 1 # 배포 확인용이므로 가볍게 1대만 가동
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - name: nginx-container
          image: acrsue.azurecr.io/kbeauty-was:v3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://<엔드포인트>:3306/kbeauty?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-web-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
