server {
    listen 80;

    # /api 요청은 WAS로 포워딩 (k8s 내부 서비스 이름 사용)
    location /api {
        proxy_pass http://was-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 나머지는 React 정적 파일
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
